/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OfferingsRouteImport } from './routes/offerings'
import { Route as CredentialsRouteImport } from './routes/credentials'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BioRouteImport } from './routes/bio'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsIndexRouteImport } from './routes/posts/index'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio/index'
import { Route as PostsPostRouteImport } from './routes/posts/$post'
import { Route as PortfolioEntryRouteImport } from './routes/portfolio/$entry'

const OfferingsRoute = OfferingsRouteImport.update({
  id: '/offerings',
  path: '/offerings',
  getParentRoute: () => rootRouteImport,
} as any)
const CredentialsRoute = CredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BioRoute = BioRouteImport.update({
  id: '/bio',
  path: '/bio',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPostRoute = PostsPostRouteImport.update({
  id: '/posts/$post',
  path: '/posts/$post',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioEntryRoute = PortfolioEntryRouteImport.update({
  id: '/portfolio/$entry',
  path: '/portfolio/$entry',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bio': typeof BioRoute
  '/contact': typeof ContactRoute
  '/credentials': typeof CredentialsRoute
  '/offerings': typeof OfferingsRoute
  '/portfolio/$entry': typeof PortfolioEntryRoute
  '/posts/$post': typeof PostsPostRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/posts/': typeof PostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bio': typeof BioRoute
  '/contact': typeof ContactRoute
  '/credentials': typeof CredentialsRoute
  '/offerings': typeof OfferingsRoute
  '/portfolio/$entry': typeof PortfolioEntryRoute
  '/posts/$post': typeof PostsPostRoute
  '/portfolio': typeof PortfolioIndexRoute
  '/posts': typeof PostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bio': typeof BioRoute
  '/contact': typeof ContactRoute
  '/credentials': typeof CredentialsRoute
  '/offerings': typeof OfferingsRoute
  '/portfolio/$entry': typeof PortfolioEntryRoute
  '/posts/$post': typeof PostsPostRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/posts/': typeof PostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bio'
    | '/contact'
    | '/credentials'
    | '/offerings'
    | '/portfolio/$entry'
    | '/posts/$post'
    | '/portfolio/'
    | '/posts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bio'
    | '/contact'
    | '/credentials'
    | '/offerings'
    | '/portfolio/$entry'
    | '/posts/$post'
    | '/portfolio'
    | '/posts'
  id:
    | '__root__'
    | '/'
    | '/bio'
    | '/contact'
    | '/credentials'
    | '/offerings'
    | '/portfolio/$entry'
    | '/posts/$post'
    | '/portfolio/'
    | '/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BioRoute: typeof BioRoute
  ContactRoute: typeof ContactRoute
  CredentialsRoute: typeof CredentialsRoute
  OfferingsRoute: typeof OfferingsRoute
  PortfolioEntryRoute: typeof PortfolioEntryRoute
  PostsPostRoute: typeof PostsPostRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
  PostsIndexRoute: typeof PostsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/offerings': {
      id: '/offerings'
      path: '/offerings'
      fullPath: '/offerings'
      preLoaderRoute: typeof OfferingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credentials': {
      id: '/credentials'
      path: '/credentials'
      fullPath: '/credentials'
      preLoaderRoute: typeof CredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bio': {
      id: '/bio'
      path: '/bio'
      fullPath: '/bio'
      preLoaderRoute: typeof BioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$post': {
      id: '/posts/$post'
      path: '/posts/$post'
      fullPath: '/posts/$post'
      preLoaderRoute: typeof PostsPostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$entry': {
      id: '/portfolio/$entry'
      path: '/portfolio/$entry'
      fullPath: '/portfolio/$entry'
      preLoaderRoute: typeof PortfolioEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BioRoute: BioRoute,
  ContactRoute: ContactRoute,
  CredentialsRoute: CredentialsRoute,
  OfferingsRoute: OfferingsRoute,
  PortfolioEntryRoute: PortfolioEntryRoute,
  PostsPostRoute: PostsPostRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
  PostsIndexRoute: PostsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
